version: '3.1'

services: 
  db:
    image: mysql
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3306:3306"

  todo:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/workspace
